all:
	mingw32-make -e -C orensemble
	move orensemble\boostrank-predict.exe .
	move orensemble\boostrank-train.exe .
	copy "orensemble\libgcc_s_seh-1.dll" .
	copy "orensemble\libstdc++-6.dll" .
	copy "orensemble\libwinpthread-1.dll" .
