
Utilities.runExperiments('tests/scriptPOM')
Utilities.runExperiments('tests/scriptELMOR')
Utilities.runExperiments('tests/scriptFHSVM')
Utilities.runExperiments('tests/scriptKDLOR')
Utilities.runExperiments('tests/scriptORBoostAllPer')
Utilities.runExperiments('tests/scriptPOM')
Utilities.runExperiments('tests/scriptREDSVM')
Utilities.runExperiments('tests/scriptSVC1_1')
Utilities.runExperiments('tests/scriptSVC1_A')
Utilities.runExperiments('tests/scriptSVC1_AOrdinal')
Utilities.runExperiments('tests/scriptSVOREX')
Utilities.runExperiments('tests/scriptSVORIM')
Utilities.runExperiments('tests/scriptSVORIMLIBSVM')
Utilities.runExperiments('tests/scriptSVR')